# Generated by Django 5.2.5 on 2025-08-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_kurslar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kurslar',
        ),
        migrations.DeleteModel(
            name='Vazifalar',
        ),
    ]
