# Generated by Django 5.2.5 on 2025-08-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('text', models.TextField()),
                ('text2', models.TextField()),
                ('text1', models.TextField()),
            ],
        ),
    ]
