# Generated by Django 5.2.5 on 2025-08-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurslar',
            name='text',
        ),
        migrations.RemoveField(
            model_name='kurslar',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='kurslar',
            name='text2',
        ),
        migrations.AddField(
            model_name='kurslar',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kurslar',
            name='status',
            field=models.CharField(choices=[('Aktiv', 'Aktiv'), ('Passiv', 'Passiv')], default='Aktiv', max_length=10),
        ),
    ]
