# Generated by Django 5.2.5 on 2025-08-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0002_remove_kurslar_text_remove_kurslar_text1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurslar',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
