# Generated by Django 5.2.5 on 2025-08-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh', models.TextField()),
                ('sana', models.DateField(auto_now=True)),
                ('uqituvchi', models.TextField()),
                ('kelganlar', models.TextField()),
            ],
        ),
    ]
