# Generated by Django 5.2.5 on 2025-08-29 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurslar', '0003_alter_kurslar_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oquvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('kurs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kurslar.kurslar')),
            ],
        ),
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('attended', models.BooleanField(default=False)),
                ('guruh', models.CharField(blank=True, max_length=255)),
                ('uqituvchi', models.CharField(blank=True, max_length=255)),
                ('oquvchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='davomat.oquvchilar')),
            ],
        ),
    ]
