# Generated by Django 5.2.5 on 2025-08-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davomat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='oquvchi',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
