# Generated by Django 5.2.5 on 2025-08-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tulovlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uquvchi', models.CharField(max_length=255)),
                ('guruh', models.TextField()),
                ('tulangan', models.TextField()),
                ('sana', models.DateField(auto_now=True)),
            ],
        ),
    ]
