# Generated by Django 5.2.5 on 2025-08-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tulovlar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tulovlar',
            name='guruh',
        ),
        migrations.RemoveField(
            model_name='tulovlar',
            name='tulangan',
        ),
        migrations.AddField(
            model_name='tulovlar',
            name='holat',
            field=models.CharField(choices=[('To‘langan', 'To‘langan'), ('Kutilmoqda', 'Kutilmoqda')], default='To‘langan', max_length=20),
        ),
        migrations.AddField(
            model_name='tulovlar',
            name='miqdor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tulovlar',
            name='sana',
            field=models.DateField(),
        ),
    ]
